#!/bin/bash
#2019/3/10
#狼战士的牙
#基于vsftpd搭建ftp
#依赖包 libdb-utils   当然还需要vsftpd的软件包  rpm方式就可以

#全局变量
v1="/etc/vsftpd/vsftpd.conf"
v2="/etc/vsftpd"

#全局函数
line(){
jiange=0.1
xunhuan=0
while true 
do
	let xunhuan++
	case $xunhuan in
	"1")
		echo  -e '\e[1;33m-\e[0m'"\b\c"
		sleep  $jiange
	;;
	"2")
		echo  -e '\e[1;33m\\\e[0m'"\b\c"
		sleep $jiange
	;;
	"3")
		echo   -e "\e[1;33m|\e[0m\b\c"
		sleep $jiange
	;;
	"4")
		echo  -e "\e[1;33m/\e[0m\b\c"
		sleep $jiange
	;;
	*)
		xunhuan=0
	;;
	esac	
done
}
line &

#关闭防火墙
echo -e  "\e[1;34m   正在关闭所有防火墙   \e[0m"
iptables -F  &>/dev/null
systemctl  stop  firewalld  &>/dev/null
setenforce 0   &>/dev/null

#首先检测依赖软件包 是否安装了
for i in  'libdb-utils   vsftpd   ftp';do
	rpm -q  $i  &>/dev/null
	if [ ! $? -eq 0   ];then
		echo " installing   $i"
		yum -y install  $i  &>/dev/null
	fi
done

#查看是否安装成功了
for  j  in  'libdb-utils  vsftpd  ftp';do
	rpm -q  $i  &>/dev/null
	if [ !  $?  -eq 0  ];then
		echo "$i 安装失败，请检查yum源！"
		exit 1
	fi
done

#给源配置文件做个备份
yes|cp  /etc/vsftpd/vsftpd.conf  /etc/vsftpd/vsftpd.conf  &>/dev/null

#开始向服务的主配置文件写入配置
#询问匿名访问是否开启
read  -p "是否开启匿名用户登录(y|n):"  pz1
if [ $pz1 ==  y  ];then
        sed -ri '/anonymous_enable/ s/(.*)=(.*)/\1=YES/'  $v1
else
        sed -ri '/anonymous_enable/ s/(.*)=(.*)/\1=NO/'   $v1
fi

#询问是否建立本地用户
read  -p "是否开启本地用户登录(y|n):" pz2
if [ $pz2  == y  ];then
        sed -ri '/local_enable/  s/(.*)=(.*)/\1=YES/'  $v1
else
        sed -ri '/local_enable/  s/(.*)=(.*)/\1=NO/'   $v1
fi

#函数
FTP1(){
	if [  ! -z $i   ] ;then
        	mkdir /home/ftp110/$i  &>/dev/null
	fi

}
FTP2(){
        if  [  -z  $i  ];then
                echo '' 
        else
cat <<-EOF >/etc/vsftpd/dir/$i
local_root=/home/ftp110/$i
rite_enable=YES
anon_upload_enable=YES
anon_world_readable_only=YES
anon_mkdir_write_enable=YES
anon_other_write_enable=YES
EOF
        fi
}

#询问是否开启虚拟用户
read -p  "是否开启虚拟的映射用户(y|n):"  pz3
if  [  $pz3 == y   ];then
	touch  list.list
	sed -ri '/local_enable/  s/(.*)=(.*)/\1=YES/'  $v1
	[ -d /etc/vsftpd/dir  ] || mkdir /etc/vsftpd/dir  &>/dev/null
	useradd -s /sbin/nologin   ftp110  &>/dev/null
	read -p   "请输入虚拟用户的账号,空格作为分割,最多五个:" zh1 zh2 zh3 zh4 zh5
	read -sp  "请输入相对应虚拟用户的密码:" mm1 mm2 mm3 mm4 mm5
	for i in "$zh1 $zh2 $zh3 $zh4 $zh5";do
		FTP1
	done
	chown -R ftp110.ftp110 /home/ftp110
	chmod 755  /home/ftp110 -R
	cat <<-EOF >/etc/vsftpd/list.list
	$zh1
	$mm1
	$zh2
	$mm2
	$zh3
	$mm3
	$zh4
	$mm4
	$zh5
	$mm5
	EOF

	db_load -T -t hash  -f  $v2/list.list  $v2/list.db  &>/dev/null
	
	grep "guest_enable="  $v1  &>/dev/null
	if [ $? -ne 0  ];then
		sed -ri '$a guest_enable=YES'   $v1
	else
		sed -ri '/guest_enable=/  s/(.*)=(.*)/\1=YES/' $v1
	fi

	grep  "guest_username=ftp110"  $v1  &>/dev/null
	if [  $? -ne 0 ];then
		sed -ri '$a guest_username=ftp110' $v1
	else
		sed -ri  '/guest_username=/ s/(.*)=(.*)/\1=ftp110/' $v1
	fi
	
	grep  "user_config_dir=" $v1  &>/dev/null
	if [ $? -ne 0 ];then
		sed -ri '$a user_config_dir=/etc/vsftpd/dir' $v1
	else
		sed -ri '/user_config_dir=/ s@(.*)=(.*)@\1=/etc/vsftpd/dir@' $v1
	fi

	grep 'virtual_use_local_privs=' $v1 &>/dev/null
	if [ $? -ne 0 ];then
		sed -ri '$a virtual_use_local_privs=YES'    $v1
	else
		sed -ri '/virtual_use_local_privs=/  s/(.*)=(.*)/\1=YES/' $v1
	fi

#对登陆验证文件进行调整
	yes|cp /etc/pam.d/vsftpd   /etc/pam.d/vsftpd.bak
	sed -ri '1i#%PAM-1.0' /etc/pam.d/vsftpd
	sed -ri '1a\auth       required     pam_userdb.so   db=/etc/vsftpd/list' /etc/pam.d/vsftpd
	sed -ri '2a\account    required     pam_userdb.so   db=/etc/vsftpd/list' /etc/pam.d/vsftpd
	sed -ri '4,$ d' /etc/pam.d/vsftpd	
fi

#略微优化ftp:开启全局禁止切换根目录
sed -ri '/chroot_local_user=YES/ s/(.*)chroot(.*)=(.*)/chroot\2=YES/'  $v1
grep "allow_writeable_chroot="  $v1  &>/dev/null
if [ $? -ne 0  ];then
	sed -ri '/chroot_local_user=YES/i allow_writeable_chroot=YES'  $v1
else
	sed -ri '/allow_writeable_chroot/ s/(.*)=(.*)/\1=YES/'  $v1
fi

#启动vsftpd服务
echo 
systemctl start  vsftpd &>/dev/null
if [ $? -eq 0  ];then
	echo -e  "\e[1;33m 服务启动成功 \e[0m"
fi
kill -9  $! &>/dev/null
exit 0
