#!/bin/bash
#狼战士的牙
#2019/3/13
#php源码安装php-5.6.39

#判断是否有/opt/web/php-5.6.39.tar.gz
[ -d /opt/web  ]
if [ $? -ne 0  ];then
	echo '请将php-5.6.39.tar.gz放在/opt/web/下'
	exit 254
fi

ls /opt/web|egrep  php-5.6.39.tar.gz &>/dev/null
if  [  $? -ne 0  ];then
	echo '请将php-5.6.39.tar.gz放在/opt/web/下'
	exit 253
fi

ls /opt/web|egrep  zend-loader-php5.6-linux-x86_64_update1.tar.gz &>/dev/null
if  [  $? -ne 0  ];then
	echo '请将zend-loader-php5.6-linux-x86_64_update1.tar.gz放在/opt/web/下'
	exit 250
fi
#判断依赖包
for i in  gd libxml2-devel  libjpeg-turbo-devel libpng-devel 
do
	rpm -q  $i &>/dev/null
	if [ $? -ne 0  ];then
		echo "installing  $i"
		yum -y install $i &>/dev/null
	fi
done

#解压编译
[ -d /usr/src/php-5.6.39  ]||tar xf /opt/web/php-5.6.39.tar.gz  -C /usr/src
cd /usr/src/php-5.6.39
[ -d /usr/local/php5 ]||./configure  --prefix=/usr/local/php5  --with-gd  --with-zlib --with-mysql=/usr/local/mysql --with-mysqli=/usr/local/mysql/bin/mysql_config  --with-config-file-path=/usr/local/php5  --enable-mbstring  --enable-fpm  --with-jpeg-dir=/usr/lib  && make  && make install

if [ $? -ne 0 ];then
	echo -e '\e[1;33m php5编译失败 \e[0m'
	exit  253
else
	echo -e '\e[1;33m 编译成功  \e[0m'
fi

#安装后调整
[ -f /usr/local/php5/php.ini ]||cp php.ini-production /usr/local/php5/php.ini
ln -s /usr/local/php5/bin/*  /usr/local/  &>/dev/null
ln -s /usr/local/php5/sbin/*  /usr/local/sbin	&>/dev/null

#解压
[-d /usr/sec/zend-loader-php5.6-linux-x86_64 ]||tar xf /opt/web/zend-loader-php5.6-linux-x86_64_update1.tar.gz -C /usr/src
cd  /usr/src/zend-loader-php5.6-linux-x86_64
[ -f /usr/local/php5/lib/php/ZendGuardLoader.so  ]||cp ZendGuardLoader.so  /usr/local/php5/lib/php/

grep 'zend_extension='  /usr/local/php5/php.ini  &>/dev/null
if  [  $? -ne  0  ];then

	sed -ri '$a zend_extension=/usr/local/php5/lib/php/ZendGuardLoader.so'  /usr/local/php5/php.ini
else
	sed -ri '/zend_extension=/ s/(.*)=(.*)/\1=/usr/local/php5/lib/php/ZendGuardLoader.so/'  /usr/local/php5/php.ini
fi

grep 'zend_loader.enable='  /usr/local/php5/php.ini  &>/dev/null
if [ $? -ne 0  ];then
	sed -ri '$a zend_loader.enable=1' /usr/local/php5/php.ini
else
	sed -ri '/zend_loader.enable=/  s/(.*)=(.*)/\1=1/'  /usr/local/php5/php.ini
fi

# 对nginx进行调整使其支持php
cd /usr/local/php5/etc
[ -f /usr/local/php5/etc/php-fpm.conf  ]||cp  php-fpm.conf.default  php-fpm.conf 
cat /ect/passwd |egrep -w ^php &>/dev/null
if [  $? -ne  0  ];then
	useradd -M -s /sbin/nologin php 
fi

sed -ri '/pid =/ s/(.*)=(.*)/pid =\2/' /usr/local/php5/etc/php-fpm.conf
sed -ri '/user =/ s/(.*)=(.*)/\1= php/' /usr/local/php5/etc/php-fpm.conf
sed -ri '/group =/ s/(.*)=(.*)/\1= php/' /usr/local/php5/etc/php-fpm.conf
sed -ri '/pm.start_servers =/ s/(.*)=(.*)/\1= 20/' /usr/local/php5/etc/php-fpm.conf
sed -ri '/pm.min_spare_servers =/ s/(.*)=(.*)/\1= 5/' /usr/local/php5/etc/php-fpm.conf
sed -ri '/pm.max_spare_servers =/ s/(.*)=(.*)/\1= 35/' /usr/local/php5/etc/php-fpm.conf
sed -ri '/pm.max_children =/ s/(.*)=(.*)/\1= 50/'  /usr/local/php5/etc/php-fpm.conf

#启动fpm模块
/usr/local/sbin/php-fpm

#撰写fpm模块启动脚本
touch /etc/init.d/fpm
echo '1'>/etc/init.d/fpm
sed -ri '$a#!/bin/bash\
#chkconfig: 2345 99 20\
#description:php-fpm Server Control Script\
FPROG="/usr/local/sbin/php-fpm"\
FPIDF="/usr/local/php5/var/run/php-fpm.pid"\
case "$1" in\
start)\
        $FPROG\
;;\
stop)\
        kill -s QUIT  $(cat $FPIDF)\
;;\
restart)\
        $0 stop\
        $0 start\
;;\
reload)\
        kill -s HUP $(cat $FPIDF)\
;;\
*)\
        echo "Usage:$0{start|stop|restart|reload}"\
        exit 1\
;;\
esac\
exit 0' /etc/init.d/fpm
sed -ri '1d' /etc/init.d/fpm
chmod +x /etc/init.d/fpm
chkconfig  --add fpm

#
